CREATE TABLE tb_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(100) NOT NULL,
    birth_date DATE NOT NULL,
    document VARCHAR(20) NOT NULL,
    
    -- Address Fields (Embedded/Flat)
    address_line VARCHAR(255) NOT NULL,
    address_number VARCHAR(10) NOT NULL,
    city VARCHAR(50) NOT NULL,
    state VARCHAR(2) NOT NULL,
    zip VARCHAR(10) NOT NULL,
    
    -- Audit Fields (TIMESTAMP WITH TIME ZONE para Instant)
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE,
    
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uc_users_document UNIQUE (document)
);